name: transisi_recruitment_test
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  bloc: ^8.1.2
  cached_network_image: ^3.2.3
  dartz: ^0.10.1
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_cache_manager: ^3.3.1
  flutter_easyloading: ^3.0.5
  flutter_screenutil: ^5.8.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  material_symbols_icons: ^4.2668.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/